[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
voip_staking = "FbjoWqP1LBfWNSYv8JQoanCnu8XwNfb738Dqw5aHgEpP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/cenwadike/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
